# Copyright 2022 The Magma Authors.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: AGW Build & Publish & Test Container

on:
  workflow_dispatch:
    inputs:
      registry:
        type: string
        description: Overwrite registry (default agw-test.artifactory.magmacore.org).
      image-prefix:
        type: string
        description: "When testing on your fork against Dockerhub, set this to your username followed by slash"
  push:
    branches:
      - master
      - 'v1.*'
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  registry: ${{ inputs.registry || 'agw-test.artifactory.magmacore.org' }}

jobs:

  build-containers:
    outputs:
      digest-c: ${{ steps.docker-builder-c.outputs.digest }}
      digest-python: ${{ steps.docker-builder-python.outputs.digest }}
      digest-go: ${{ steps.docker-builder-go.outputs.digest }}
      registry: ${{ steps.set-registry-output.outputs.registry }}
      image-prefix: ${{ steps.set-image-prefix.outputs.prefix }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Registry is ${{ env.registry }}"

      - id: set-registry-output
        name: Set registry output
        run: |
          echo ${{ env.registry }}
          echo registry=${{ env.registry }} >> $GITHUB_OUTPUT

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0

      - name: verify registry output
        run: echo Registry is ${{ steps.set-registry-output.outputs.registry }}

      - id: get-short-git-sha
        name: Set short git sha output
        run: |
          echo ${GITHUB_SHA:0:8}
          echo sha=${GITHUB_SHA:0:8} >> $GITHUB_OUTPUT

      - name: verify git sha output
        run: echo git sha is ${{ steps.get-short-git-sha.outputs.sha }}

      - id: set-image-prefix
        name: Set image-prefix output
        run: |
          echo ${{ inputs.image-prefix }}
          echo prefix=${{ inputs.image-prefix }} >> $GITHUB_OUTPUT

      - name: verify image prefix output
        run: echo image-prefix is ${{ steps.set-image-prefix.outputs.image-prefix }}

      - uses: ./.github/workflows/composite/docker-builder-agw
        id: docker-builder-c
        with:
          REGISTRY_USERNAME: ${{ secrets.JFROG_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          REGISTRY: ${{ env.registry }}
          FILE: lte/gateway/docker/services/c/Dockerfile
          TAGS: ${{ env.registry }}/${{ inputs.image-prefix }}agw_gateway_c:${{ steps.get-short-git-sha.outputs.sha }}
      - run: echo "C container image digest is ${{ steps.docker-builder-c.outputs.digest }}"
      - run: echo "docker-builder-c conclusion = ${{ steps.docker-builder-c.conclusion }}"

      - uses: ./.github/workflows/composite/docker-builder-agw
        id: docker-builder-python
        with:
          REGISTRY_USERNAME: ${{ secrets.JFROG_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          REGISTRY: ${{ env.registry }}
          FILE: lte/gateway/docker/services/python/Dockerfile
          TAGS: ${{ env.registry }}/${{ inputs.image-prefix }}agw_gateway_python:${{ steps.get-short-git-sha.outputs.sha }}
      - run: echo "Python container image digest is ${{ steps.docker-builder-python.outputs.digest }}"
      - run: echo "docker-builder-python conclusion = ${{ steps.docker-builder-python.conclusion }}"

      - uses: ./.github/workflows/composite/docker-builder-agw
        id: docker-builder-go
        with:
          REGISTRY_USERNAME: ${{ secrets.JFROG_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          REGISTRY: ${{ env.registry }}
          FILE: feg/gateway/docker/go/Dockerfile
          TAGS: ${{ env.registry }}/${{ inputs.image-prefix }}gateway_go:${{ steps.get-short-git-sha.outputs.sha }}
      - run: echo "Go container image digest is ${{ steps.docker-builder-go.outputs.digest }}"
      - run: echo "docker-builder-go conclusion = ${{ steps.docker-builder-go.conclusion }}"

  build-containers-ghz:
    runs-on: ubuntu-latest
    needs: build-containers
    steps:
      - run: echo "Registry is  ${{ env.registry }}"

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0

      - id: get-short-git-sha
        run: echo sha=${GITHUB_SHA:0:8} >> $GITHUB_OUTPUT

      - uses: ./.github/workflows/composite/docker-builder-agw
        with:
          REGISTRY_USERNAME: ${{ secrets.JFROG_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          REGISTRY: ${{ env.registry }}
          TAGS: ${{ env.registry }}/${{ inputs.image-prefix }}ghz_gateway_c:${{ steps.get-short-git-sha.outputs.sha }}
          CONTEXT: lte/gateway/docker/ghz

      - uses: ./.github/workflows/composite/docker-builder-agw
        with:
          REGISTRY_USERNAME: ${{ secrets.JFROG_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          REGISTRY: ${{ env.registry }}
          TAGS: ${{ env.registry }}/${{ inputs.image-prefix }}ghz_gateway_python:${{ steps.get-short-git-sha.outputs.sha }}
          CONTEXT: lte/gateway/docker/ghz

  verify-outputs:
    needs: build-containers
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo digest-c ${{ needs.build-containers.outputs.digest-c }}
          echo digest-python ${{ needs.build-containers.outputs.digest-python }}
          echo digest-go ${{ needs.build-containers.outputs.digest-go }}
          echo registry ${{ needs.build-containers.outputs.registry }}
          echo image-prefix ${{ needs.build-containers.outputs.image-prefix }}
          echo test-targets precommit

  test-containers-precommit:
    needs: build-containers
    # We only want to trigger the tests if the build-containers job uploaded the images.
    # The following condition is a crude heuristic for this limitation.
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/lte-integ-test-containerized.yml
    with:
      digest-c: ${{ needs.build-containers.outputs.digest-c }}
      digest-python: ${{ needs.build-containers.outputs.digest-python }}
      digest-go: ${{ needs.build-containers.outputs.digest-go }}
      registry: ${{ needs.build-containers.outputs.registry }}
      image-prefix: ${{ needs.build-containers.outputs.image-prefix }}
      test-targets: precommit

  test-containers-extended:
    needs: build-containers
    # We only want to trigger the tests if the build-containers job uploaded the images.
    # The following condition is a crude heuristic for this limitation.
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/lte-integ-test-containerized.yml
    with:
      digest-c: ${{ needs.build-containers.outputs.digest-c }}
      digest-python: ${{ needs.build-containers.outputs.digest-python }}
      digest-go: ${{ needs.build-containers.outputs.digest-go }}
      registry: ${{ needs.build-containers.outputs.registry }}
      image-prefix: ${{ needs.build-containers.outputs.image-prefix }}
      test-targets: extended
