name: debug-arm-workflow-shell

on:
  workflow_dispatch:
    inputs:
      MAGMA_REPO_URL:
        type: string
        default: "https://github.com/magma/magma.git"
      MAGMA_BRANCH:
        type: string
        default: master

permissions:
  id-token: write  # required for OIDC auth to AWS

jobs:
  build-deploy-arm-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "url: ${{ inputs.MAGMA_REPO_URL }}"
          echo "branch: ${{ inputs.MAGMA_BRANCH }}"
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::269966122452:role/github_actions"
          role-session-name: debug_arm_workflow
          aws-region: us-east-1
      - name: Install Dependencies
        run: |
          pip install awscli boto3
      - name: Setup SSH
        run: |
          mkdir ~/.ssh && chmod go-rwx ~/.ssh
          echo "${{ secrets.AWS_JAN_EC2_GITHUB_ACTIONS_RSA }}" > ~/.ssh/id_rsa
          chmod go-rwx ~/.ssh/id_rsa
      - name: Run the shell script to build on graviton
        run: |
          export MAGMA_REPO_URL=${{ inputs.MAGMA_REPO_URL }}
          echo $MAGMA_REPO_URL
          export MAGMA_BRANCH=${{ inputs.MAGMA_BRANCH }}
          echo $MAGMA_BRANCH
          export DOCKER_REGISTRY_URL=agw-test.artifactory.magmacore.org
          export DOCKER_REGISTRY_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          export DOCKER_REGISTRY_PASSWORD="${{ secrets.DOCKER_PASSWORD }}"
          lte/gateway/deploy/arm_build.sh
