name: debug-ssh

on:
  workflow_dispatch:
    inputs:
      sleep_duration:
        type: string
        required: true
      extra_options:
        type: string
        default: ""
        required: false

jobs:
  ssh-and-sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          chmod go-rwx ~/.ssh
          echo "${{ secrets.AWS_JAN_EC2_GITHUB_ACTIONS_RSA }}" > ~/.ssh/id_rsa-github_actions_jan
          chmod go-rwx ~/.ssh/id_rsa-github_actions_jan
          touch ~/.ssh/known_hosts
          chmod go-rwx ~/.ssh/known_hosts
          # The host key can be retrieved from Terraform output
          echo "[52.0.2.174]:2345 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOCQ2Tm8BRzQ+iqpBz4HFo6Ua4UWlYUmpIwWdwah3IzV4OUmN29jxcu4W93wS1hk01jmFNR2XNQSqSpfcVlCtsaVT8pd3kcAe7YEw2R0lLbaHPIALRhl/HqicuWKISFB357vSRy+Bqqw/H0MNm1KFwfIgBseL2X5Cjh8Ftn78EDhf8VRCj5Rt2ZF5hAX+eJyHEhX5htCtc5R3k4tRnWYwD2Jy9L+J2nHq6t96XdweKTwFLQaxPHTliXcJ4Ox6ku26g6j3BPc9rXvrfNfCYASeEbKF2rmhZ4cpd3XlXjYceiZAunlqcLSMBqMWdrKX66mJxJphsuZpKlVruJhJUOit4rHLMVb6B1Epd5ewcZjQO7w2XOcGJVGSzUUUkN7Hk4DMFpRzeTnolVXFiaaQg5RRC3ZJLCLtUW1MAKDNyQaUl6Q5y80gAVs/Dipx0l6zRxoONXScikTBbMHOJp9flB8++z8iixN48/L6CPe1EOOcVuU7P5PboKpLJFF1f8s1RZyjSJty6/v/7oy/nm+YJ/1nn7MI69KlyaU/SIOxJYUE7yr0l77sC/4HVhKrgiy/yqeXXNHCXRYoYtafAcGg5gAqRl8tkN0xBL+x8/G19B/k6ULf+iSc3nFgPBUa1NW4uFcCjyWjkhqdnnXYkiat91Mvsr7r+UrRYOVpCzDKS5vTr5w==" >> ~/.ssh/known_hosts
      - name: SSH and sleep
        run: |
          date
          echo "SSH & Sleeping for ${{ inputs.sleep_duration }}"
          echo "Extra options are ${{ inputs.extra_options }}"
          ssh -p 2345 -i ~/.ssh/id_rsa-github_actions_jan ${{ inputs.extra_options }} ubuntu@52.0.2.174 sleep "${{ inputs.sleep_duration }}"
          echo "Done with SSH"
          date
